const date = (value) => new Date(`${value}T00:00:00.000Z`);
const timestamp = (value) => new Date(value);

export function makeTransactionRow(overrides = {}) {
  return {
    id: 1,
    date: date("2026-01-15"),
    amount: "-12.5000",
    currency: "EUR",
    balance: null,
    memo: "Test transaction",
    comment: null,
    bank_account: "Main",
    account_id: 1,
    recipient_id: 1,
    recipient_bank_account_id: null,
    category_id: 1,
    is_active: true,
    import_batch_id: null,
    matched_pattern_id: null,
    tx_hash: null,
    is_transfer: false,
    transfer_peer_id: null,
    transfer_source: null,
    recipient_name: "Test recipient",
    category_name: "TEST:GENERAL",
    tags: [],
    created_at: timestamp("2026-01-15T10:00:00.000Z"),
    updated_at: timestamp("2026-01-15T10:00:00.000Z"),
    ...overrides,
  };
}

export function makePlannedTransactionRow(overrides = {}) {
  return {
    id: 1,
    planned_date: date("2026-02-01"),
    amount: "-50.0000",
    currency: "EUR",
    memo: "Planned payment",
    comment: null,
    url: null,
    bank_account: "Main",
    account_id: 1,
    recipient_id: 1,
    category_id: 1,
    is_recurring: false,
    recurrence_pattern: null,
    recurrence_end_date: null,
    max_occurrences: null,
    reminder_days_before: null,
    is_loan: false,
    loan_type: null,
    loan_principal: null,
    loan_annual_interest_rate: null,
    loan_term_months: null,
    loan_start_date: null,
    loan_payment_day: null,
    loan_regular_payment_amount: null,
    loan_first_payment_date: null,
    is_executed: false,
    last_executed_date: null,
    is_active: true,
    recipient_name: "Test recipient",
    category_name: "TEST:GENERAL",
    executions: [],
    execution_count: 0,
    executed_transaction_id: null,
    loan_schedule: [],
    tags: [],
    created_at: timestamp("2026-01-01T10:00:00.000Z"),
    updated_at: timestamp("2026-01-01T10:00:00.000Z"),
    ...overrides,
  };
}

export function makeInvestmentRow(overrides = {}) {
  return {
    id: 1,
    name: "Test investment",
    symbol: "TEST",
    asset_class: "stock",
    currency: "EUR",
    current_price: 100,
    interest_rate: null,
    maturity_date: null,
    location: null,
    municipality: null,
    cadastral_income: null,
    municipality_tax_rate: null,
    notes: null,
    is_active: true,
    price_provider: "manual",
    price_provider_id: null,
    price_provider_url: null,
    price_provider_latest_url: null,
    price_provider_latest_path: null,
    price_provider_history_url: null,
    price_provider_history_path: null,
    price_provider_history_ts_path: null,
    price_provider_history_price_path: null,
    price_updated_at: null,
    show_in_ticker: true,
    created_at: timestamp("2026-01-01T10:00:00.000Z"),
    updated_at: timestamp("2026-01-01T10:00:00.000Z"),
    ...overrides,
  };
}

export function makePortfolioTransactionRow(overrides = {}) {
  return {
    id: 1,
    investment_id: 1,
    type: "buy",
    date: "2026-01-15",
    amount: 1000,
    units: 10,
    price_per_unit: 100,
    fees: 0,
    taxes: 0,
    currency: "EUR",
    fx_rate_to_eur: 1,
    note: null,
    is_recurring: false,
    recurrence_interval: null,
    recurrence_end_date: null,
    account_id: 1,
    import_batch_id: null,
    created_at: timestamp("2026-01-15T10:00:00.000Z"),
    updated_at: timestamp("2026-01-15T10:00:00.000Z"),
    ...overrides,
  };
}

export function makeImportStagingRow(overrides = {}) {
  return {
    id: "1",
    batch_id: "1",
    row_index: 0,
    status: "pending",
    tx_date: date("2026-01-15"),
    bank_account: "Main",
    recipient_raw: "Test recipient",
    memo: "Imported transaction",
    amount: "-12.5000",
    currency: "EUR",
    balance: "1000.0000",
    recipient_account: null,
    recipient_address: null,
    recipient_bank_name: null,
    comment: null,
    raw_data: "synthetic,test,row",
    tx_hash: "test-hash",
    resolved_recipient_id: null,
    resolved_bank_account_id: null,
    error_message: null,
    match_source: null,
    matched_pattern_id: null,
    match_similarity: null,
    user_override_recipient_id: null,
    override_category_id: null,
    created_at: timestamp("2026-01-15T10:00:00.000Z"),
    ...overrides,
  };
}

export function makePortfolioImportStagingRow(overrides = {}) {
  return {
    id: "1",
    batch_id: "1",
    row_index: 0,
    status: "pending",
    tx_date: date("2026-01-15"),
    type_raw: "BUY",
    type: "buy",
    symbol_raw: "TEST",
    name_raw: "Test investment",
    units: "10.00000000",
    price_per_unit: "100.000000",
    amount: "1000.0000",
    fees: "0.0000",
    taxes: "0.0000",
    currency: "EUR",
    fx_rate_to_eur: "1.0000000000",
    note: null,
    raw_data: "synthetic,portfolio,row",
    tx_hash: "portfolio-test-hash",
    resolved_investment_id: null,
    user_override_investment_id: null,
    match_source: null,
    match_similarity: null,
    committed_txn_id: null,
    error_message: null,
    route: "portfolio",
    created_at: timestamp("2026-01-15T10:00:00.000Z"),
    ...overrides,
  };
}
