/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions */
        get: operations["getTransactions"];
        put?: never;
        /** Create transaction */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get transaction */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /** Delete transaction */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /** Update transaction */
        patch: operations["updateTransaction"];
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories */
        get: operations["getCategories"];
        put?: never;
        /** Create or get existing category */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get category */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        /** Delete category */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /** Update category */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/api/recipients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recipients */
        get: operations["getRecipients"];
        put?: never;
        /** Create or get existing recipient */
        post: operations["createRecipient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get recipient */
        get: operations["getRecipient"];
        put?: never;
        post?: never;
        /** Delete recipient */
        delete: operations["deleteRecipient"];
        options?: never;
        head?: never;
        /** Update recipient */
        patch: operations["updateRecipient"];
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all settings */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        /** Get single setting */
        get: operations["getSetting"];
        /** Save setting */
        put: operations["saveSetting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List investments */
        get: operations["getInvestments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/net-worth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get net worth summary */
        get: operations["getNetWorth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saved-charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved charts */
        get: operations["getSavedCharts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            ok: boolean;
            /** @description Present on success */
            data?: unknown;
            error?: components["schemas"]["ErrorPayload"];
        };
        ErrorPayload: {
            message: string;
            code?: string;
            status?: number;
        };
        Link: {
            rel: string;
            href: string;
            method: string;
            title?: string;
        };
        PaginationMeta: {
            total: number;
            limit: number;
            offset: number;
        };
        Category: {
            id: number;
            general: string;
            detail: string;
            description?: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            links: components["schemas"]["Link"][];
        };
        CategoryCreate: {
            general: string;
            detail: string;
            description?: string;
        };
        CategoryUpdate: {
            general?: string;
            detail?: string;
            description?: string;
            is_active?: boolean;
        };
        CategoryList: components["schemas"]["PaginationMeta"] & {
            items: components["schemas"]["Category"][];
            links: components["schemas"]["Link"][];
        };
        Recipient: {
            id: number;
            name: string;
            primary_bank_account?: string;
            default_category_id?: number;
            default_category_name?: string;
            primary_recipient_id?: number | null;
            primary_recipient_name?: string | null;
            alias_count?: number;
            notes?: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            links: components["schemas"]["Link"][];
        };
        RecipientCreate: {
            name: string;
            default_category_id?: number;
            notes?: string;
        };
        RecipientUpdate: {
            name?: string;
            default_category_id?: number | null;
            notes?: string;
            is_active?: boolean;
        };
        RecipientList: components["schemas"]["PaginationMeta"] & {
            items: components["schemas"]["Recipient"][];
            links: components["schemas"]["Link"][];
        };
        Transaction: {
            id: number;
            /**
             * Format: date
             * @description YYYY-MM-DD
             */
            transaction_date: string;
            bank_account: string;
            recipient_id?: number;
            recipient_name?: string;
            memo?: string;
            /** Format: double */
            amount: number;
            /** Format: double */
            amount_eur?: number;
            currency?: string;
            /** Format: double */
            balance?: number;
            category_id?: number;
            /** @description Format: GENERAL:DETAIL */
            category_name?: string;
            comment?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            links: components["schemas"]["Link"][];
        };
        TransactionCreate: {
            /** Format: date */
            transaction_date: string;
            bank_account: string;
            recipient_id: number;
            memo?: string;
            amount: number;
            currency?: string;
            balance?: number;
            category_id?: number;
            comment?: string;
        };
        TransactionUpdate: {
            /** Format: date */
            transaction_date?: string;
            bank_account?: string;
            recipient_id?: number;
            recipient_name?: string;
            memo?: string;
            amount?: number;
            currency?: string;
            balance?: number;
            category_id?: number;
            category_name?: string;
            comment?: string;
            is_active?: boolean;
        };
        TransactionList: components["schemas"]["PaginationMeta"] & {
            items: components["schemas"]["Transaction"][];
            links: components["schemas"]["Link"][];
        };
        /** @enum {string} */
        PlannedLoanType: "amortizing" | "fixed_principal" | "interest_only";
        PlannedLoanScheduleEntry: {
            installment_number: number;
            /** Format: date */
            due_date: string;
            payment_amount: number;
            principal_amount: number;
            interest_amount: number;
            remaining_principal: number;
        };
        PlannedTransactionExecution: {
            id: number;
            executed_transaction_id: number;
            /** Format: date */
            execution_date: string;
            /** Format: date-time */
            created_at: string;
        };
        PlannedTransaction: {
            id: number;
            /** Format: date */
            planned_date: string;
            bank_account: string;
            recipient_id?: number;
            recipient_name?: string;
            memo?: string;
            amount: number;
            currency?: string;
            category_id?: number;
            category_name?: string;
            comment?: string;
            url?: string;
            is_recurring: boolean;
            recurrence_pattern?: string;
            is_loan?: boolean;
            loan_type?: components["schemas"]["PlannedLoanType"];
            loan_principal?: number | null;
            loan_annual_interest_rate?: number | null;
            loan_term_months?: number | null;
            /** Format: date */
            loan_start_date?: string | null;
            loan_payment_day?: number | null;
            loan_regular_payment_amount?: number | null;
            /** Format: date */
            loan_first_payment_date?: string | null;
            loan_schedule?: components["schemas"]["PlannedLoanScheduleEntry"][];
            is_executed: boolean;
            /** Format: date */
            last_executed_date?: string;
            executed_transaction_id?: number;
            execution_count: number;
            executions?: components["schemas"]["PlannedTransactionExecution"][];
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            links: components["schemas"]["Link"][];
        };
        PlannedTransactionCreate: {
            /** Format: date */
            planned_date: string;
            bank_account: string;
            recipient_id: number;
            memo?: string;
            amount: number;
            currency?: string;
            category_id?: number;
            comment?: string;
            url?: string;
            is_recurring?: boolean;
            recurrence_pattern?: string;
            is_loan?: boolean;
            loan_type?: components["schemas"]["PlannedLoanType"];
            loan_principal?: number;
            loan_annual_interest_rate?: number;
            loan_term_months?: number;
            /** Format: date */
            loan_start_date?: string;
            loan_payment_day?: number;
        };
        PlannedTransactionList: components["schemas"]["PaginationMeta"] & {
            items: components["schemas"]["PlannedTransaction"][];
            links: components["schemas"]["Link"][];
        };
        /** @enum {string} */
        AssetClass: "stock" | "etf" | "crypto" | "metals" | "real_estate" | "savings" | "bond";
        /** @enum {string} */
        PortfolioTxnType: "buy" | "sell" | "dividend" | "fee" | "tax" | "interest" | "rent_income" | "appreciation" | "gift";
        /** @enum {string} */
        RecurrenceInterval: "daily" | "weekly" | "bi-weekly" | "monthly" | "quarterly" | "yearly";
        /** @enum {string} */
        PriceProvider: "manual" | "binance" | "yahoo" | "custom" | "kinesis";
        Investment: {
            id: number;
            name: string;
            symbol?: string;
            asset_class: components["schemas"]["AssetClass"];
            currency: string;
            current_price?: number;
            interest_rate?: number;
            /** Format: date */
            maturity_date?: string;
            location?: string;
            municipality?: string;
            cadastral_income?: number;
            municipality_tax_rate?: number;
            notes?: string;
            price_provider: components["schemas"]["PriceProvider"];
            price_provider_id?: string;
            price_provider_url?: string;
            price_provider_latest_url?: string;
            price_provider_latest_path?: string;
            price_provider_history_url?: string;
            price_provider_history_path?: string;
            price_provider_history_ts_path?: string;
            price_provider_history_price_path?: string;
            /** Format: date-time */
            price_updated_at?: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        InvestmentList: components["schemas"]["PaginationMeta"] & {
            items: components["schemas"]["Investment"][];
            links: components["schemas"]["Link"][];
        };
        PortfolioTransaction: {
            id: number;
            investment_id: number;
            type: components["schemas"]["PortfolioTxnType"];
            /** Format: date */
            date: string;
            amount: number;
            units?: number;
            price_per_unit?: number;
            fees?: number;
            taxes?: number;
            currency: string;
            fx_rate_to_eur?: number;
            note?: string;
            is_recurring: boolean;
            recurrence_interval?: components["schemas"]["RecurrenceInterval"];
            /** Format: date */
            recurrence_end_date?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PortfolioTransactionList: components["schemas"]["PaginationMeta"] & {
            items: components["schemas"]["PortfolioTransaction"][];
            links: components["schemas"]["Link"][];
        };
        AggregationEnvelope: {
            ok: boolean;
            cached: boolean;
            /** Format: date-time */
            generatedAt: string;
        };
        NetWorthSnapshot: {
            /** Format: date */
            date: string;
            liquid: number;
            investments: number;
            netWorth: number;
        };
        NetWorthResponse: {
            current: {
                liquid: number;
                investments: number;
                netWorth: number;
                currency: string;
            };
            monthlyChange: number;
            monthlyChangePercent: number;
            snapshots: components["schemas"]["NetWorthSnapshot"][];
            snapshotsTotal?: number;
        };
        SavedChart: {
            id: number;
            name: string;
            /** @enum {string} */
            chart_type: "line" | "bar" | "area";
            category_ids: number[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Setting: {
            key: string;
            value: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTransactions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                start_date?: string;
                end_date?: string;
                bank_account?: string;
                category_id?: number;
                recipient_id?: number;
                search?: string;
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated transaction list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TransactionList"];
                    };
                };
            };
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Created transaction */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Transaction"];
                    };
                };
            };
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Transaction"];
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Updated transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Transaction"];
                    };
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
                is_active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CategoryList"];
                    };
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Existing category returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Category"];
                    };
                };
            };
            /** @description New category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Category"];
                    };
                };
            };
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Category"];
                    };
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Updated category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Category"];
                    };
                };
            };
        };
    };
    getRecipients: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
                is_active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipient list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["RecipientList"];
                    };
                };
            };
        };
    };
    createRecipient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientCreate"];
            };
        };
        responses: {
            /** @description Existing recipient */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Recipient"];
                    };
                };
            };
            /** @description New recipient created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Recipient"];
                    };
                };
            };
        };
    };
    getRecipient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single recipient */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Recipient"];
                    };
                };
            };
        };
    };
    deleteRecipient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    updateRecipient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientUpdate"];
            };
        };
        responses: {
            /** @description Updated recipient */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Recipient"];
                    };
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All settings as key-value map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    getSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setting value */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Setting"];
                    };
                };
            };
        };
    };
    saveSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: unknown;
                };
            };
        };
        responses: {
            /** @description Saved setting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Setting"];
                    };
                };
            };
        };
    };
    getInvestments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Investment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["InvestmentList"];
                    };
                };
            };
        };
    };
    getNetWorth: {
        parameters: {
            query?: {
                currency?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Net worth with history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["NetWorthResponse"];
                    };
                };
            };
        };
    };
    getSavedCharts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved chart list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["SavedChart"][];
                    };
                };
            };
        };
    };
}
