import {
    Activity,
    ArrowLeftRight,
    BarChart3,
    Briefcase,
    Building2,
    CalendarClock,
    CandlestickChart,
    ChartSpline,
    Coins,
    Database,
    Gauge,
    Gem,
    GitCompareArrows,
    Globe,
    HandCoins,
    Import,
    Landmark,
    LayoutDashboard,
    LineChart,
    PiggyBank,
    PieChart,
    Receipt,
    Scale,
    ServerCog,
    ShieldCheck,
    Sparkles,
    Tags,
    Target,
    Telescope,
    TrendingUp,
    Users,
    Wallet,
    WalletCards,
    type LucideIcon,
} from "lucide-react";

/** Canonical identity icon for every navigable destination. */
export const PAGE_ICONS = {
    "/": LayoutDashboard,
    "/transactions": Receipt,
    "/categories": Tags,
    "/recipients": Users,
    "/statistics": BarChart3,
    "/planned": CalendarClock,
    "/owes": HandCoins,
    "/tax": Landmark,
    "/import": Import,
    "/ai-chat": Sparkles,
    "/accounts": WalletCards,
    "/portfolio": PieChart,
    "/portfolio/net-worth": Wallet,
    "/portfolio/stocks": TrendingUp,
    "/portfolio/crypto": Coins,
    "/portfolio/metals": Gem,
    "/portfolio/real-estate": Building2,
    "/portfolio/savings": PiggyBank,
    "/portfolio/performance": Gauge,
    "/portfolio/rebalance": Scale,
    "/portfolio/tax": Landmark,
    "/portfolio/import": Briefcase,
    "/research": Telescope,
    "/research/markets": Globe,
    "/research/market": LineChart,
    "/research/compare": GitCompareArrows,
    "/research/charts": CandlestickChart,
    "/research/forecast": ChartSpline,
    "/research/watchlist": Target,
    "/admin": ShieldCheck,
    "/admin/db": Database,
    "/admin/providers": ServerCog,
    "/admin/endpoints": Activity,
    "/admin/exchange-rates": ArrowLeftRight,
} as const satisfies Record<string, LucideIcon>;

export type PageIconPath = keyof typeof PAGE_ICONS;

export function pageIcon(path: PageIconPath): LucideIcon {
    return PAGE_ICONS[path];
}
