"""Initial database schema

Revision ID: a82e8e3148ec
Revises: 
Create Date: 2026-02-20 10:42:39.934835

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a82e8e3148ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_raw_ref_source'), table_name='transaction_raw_references')
    op.drop_index(op.f('ix_transaction_raw_references_id'), table_name='transaction_raw_references')
    op.drop_index(op.f('ix_transaction_raw_references_raw_source_id'), table_name='transaction_raw_references')
    op.drop_index(op.f('ix_transaction_raw_references_raw_source_type'), table_name='transaction_raw_references')
    op.drop_index(op.f('ix_transaction_raw_references_transaction_id'), table_name='transaction_raw_references')
    op.drop_table('transaction_raw_references')
    op.drop_index(op.f('idx_kbc_account_date'), table_name='kbc_raw_transactions')
    op.drop_index(op.f('idx_kbc_statement'), table_name='kbc_raw_transactions')
    op.drop_index(op.f('ix_kbc_raw_transactions_account_number'), table_name='kbc_raw_transactions')
    op.drop_index(op.f('ix_kbc_raw_transactions_deduplication_hash'), table_name='kbc_raw_transactions')
    op.drop_index(op.f('ix_kbc_raw_transactions_id'), table_name='kbc_raw_transactions')
    op.drop_index(op.f('ix_kbc_raw_transactions_transaction_date'), table_name='kbc_raw_transactions')
    op.drop_table('kbc_raw_transactions')
    op.drop_index(op.f('idx_belfius_account_date'), table_name='belfius_raw_transactions')
    op.drop_index(op.f('ix_belfius_raw_transactions_account_number'), table_name='belfius_raw_transactions')
    op.drop_index(op.f('ix_belfius_raw_transactions_deduplication_hash'), table_name='belfius_raw_transactions')
    op.drop_index(op.f('ix_belfius_raw_transactions_id'), table_name='belfius_raw_transactions')
    op.drop_index(op.f('ix_belfius_raw_transactions_transaction_date'), table_name='belfius_raw_transactions')
    op.drop_table('belfius_raw_transactions')
    op.drop_index(op.f('idx_revolut_product_date'), table_name='revolut_raw_transactions')
    op.drop_index(op.f('idx_revolut_state'), table_name='revolut_raw_transactions')
    op.drop_index(op.f('ix_revolut_raw_transactions_completed_date'), table_name='revolut_raw_transactions')
    op.drop_index(op.f('ix_revolut_raw_transactions_deduplication_hash'), table_name='revolut_raw_transactions')
    op.drop_index(op.f('ix_revolut_raw_transactions_id'), table_name='revolut_raw_transactions')
    op.drop_table('revolut_raw_transactions')
    op.drop_index(op.f('idx_custom_txn_category'), table_name='custom_transactions')
    op.drop_index(op.f('idx_custom_txn_date_account'), table_name='custom_transactions')
    op.drop_index(op.f('idx_custom_txn_recipient'), table_name='custom_transactions')
    op.drop_index(op.f('ix_custom_transactions_bank_account'), table_name='custom_transactions')
    op.drop_index(op.f('ix_custom_transactions_category_id'), table_name='custom_transactions')
    op.drop_index(op.f('ix_custom_transactions_date'), table_name='custom_transactions')
    op.drop_index(op.f('ix_custom_transactions_id'), table_name='custom_transactions')
    op.drop_index(op.f('ix_custom_transactions_recipient_id'), table_name='custom_transactions')
    op.drop_table('custom_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_transactions',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
                    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
                    sa.Column('bank_account', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
                    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'],
                                            name=op.f('custom_transactions_category_id_fkey')),
                    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'],
                                            name=op.f('custom_transactions_recipient_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('custom_transactions_pkey'))
                    )
    op.create_index(op.f('ix_custom_transactions_recipient_id'), 'custom_transactions', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_custom_transactions_id'), 'custom_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_custom_transactions_date'), 'custom_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_custom_transactions_category_id'), 'custom_transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_custom_transactions_bank_account'), 'custom_transactions', ['bank_account'], unique=False)
    op.create_index(op.f('idx_custom_txn_recipient'), 'custom_transactions', ['recipient_id', 'date'], unique=False)
    op.create_index(op.f('idx_custom_txn_date_account'), 'custom_transactions', ['date', 'bank_account'], unique=False)
    op.create_index(op.f('idx_custom_txn_category'), 'custom_transactions', ['category_id', 'date'], unique=False)
    op.create_table('revolut_raw_transactions',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('deduplication_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
                    sa.Column('product', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
                    sa.Column('started_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
                    sa.Column('fee', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
                    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
                    sa.Column('state', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
                    sa.Column('balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
                    sa.Column('raw_csv_line', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('revolut_raw_transactions_pkey'))
                    )
    op.create_index(op.f('ix_revolut_raw_transactions_id'), 'revolut_raw_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_revolut_raw_transactions_deduplication_hash'), 'revolut_raw_transactions',
                    ['deduplication_hash'], unique=True)
    op.create_index(op.f('ix_revolut_raw_transactions_completed_date'), 'revolut_raw_transactions', ['completed_date'],
                    unique=False)
    op.create_index(op.f('idx_revolut_state'), 'revolut_raw_transactions', ['state'], unique=False)
    op.create_index(op.f('idx_revolut_product_date'), 'revolut_raw_transactions', ['product', 'completed_date'],
                    unique=False)
    op.create_table('belfius_raw_transactions',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('deduplication_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.Column('account_number', sa.VARCHAR(length=34), autoincrement=False, nullable=False),
                    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=False),
                    sa.Column('statement_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('transaction_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('recipient_account', sa.VARCHAR(length=34), autoincrement=False, nullable=True),
                    sa.Column('recipient_name', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('recipient_street', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('recipient_location', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('recipient_bic', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
                    sa.Column('recipient_country', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
                    sa.Column('transaction_description', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('value_date', sa.DATE(), autoincrement=False, nullable=True),
                    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
                    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
                    sa.Column('balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
                    sa.Column('additional_message', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('raw_csv_line', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('belfius_raw_transactions_pkey'))
                    )
    op.create_index(op.f('ix_belfius_raw_transactions_transaction_date'), 'belfius_raw_transactions',
                    ['transaction_date'], unique=False)
    op.create_index(op.f('ix_belfius_raw_transactions_id'), 'belfius_raw_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_belfius_raw_transactions_deduplication_hash'), 'belfius_raw_transactions',
                    ['deduplication_hash'], unique=True)
    op.create_index(op.f('ix_belfius_raw_transactions_account_number'), 'belfius_raw_transactions', ['account_number'],
                    unique=False)
    op.create_index(op.f('idx_belfius_account_date'), 'belfius_raw_transactions',
                    ['account_number', 'transaction_date'], unique=False)
    op.create_table('kbc_raw_transactions',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('deduplication_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.Column('account_number', sa.VARCHAR(length=34), autoincrement=False, nullable=False),
                    sa.Column('category_name', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('account_holder_name', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
                    sa.Column('statement_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=False),
                    sa.Column('value_date', sa.DATE(), autoincrement=False, nullable=True),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
                    sa.Column('balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
                    sa.Column('credit_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
                    sa.Column('debit_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
                    sa.Column('counterparty_account', sa.VARCHAR(length=34), autoincrement=False, nullable=True),
                    sa.Column('counterparty_bic', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
                    sa.Column('counterparty_name', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('counterparty_address', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('structured_communication', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('free_communication', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('raw_csv_line', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('kbc_raw_transactions_pkey'))
                    )
    op.create_index(op.f('ix_kbc_raw_transactions_transaction_date'), 'kbc_raw_transactions', ['transaction_date'],
                    unique=False)
    op.create_index(op.f('ix_kbc_raw_transactions_id'), 'kbc_raw_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_kbc_raw_transactions_deduplication_hash'), 'kbc_raw_transactions', ['deduplication_hash'],
                    unique=True)
    op.create_index(op.f('ix_kbc_raw_transactions_account_number'), 'kbc_raw_transactions', ['account_number'],
                    unique=False)
    op.create_index(op.f('idx_kbc_statement'), 'kbc_raw_transactions', ['statement_number'], unique=False)
    op.create_index(op.f('idx_kbc_account_date'), 'kbc_raw_transactions', ['account_number', 'transaction_date'],
                    unique=False)
    op.create_table('transaction_raw_references',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('raw_source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
                    sa.Column('raw_source_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'],
                                            name=op.f('transaction_raw_references_transaction_id_fkey'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('transaction_raw_references_pkey')),
                    sa.UniqueConstraint('raw_source_type', 'raw_source_id', name=op.f('uq_raw_source'),
                                        postgresql_include=[], postgresql_nulls_not_distinct=False)
                    )
    op.create_index(op.f('ix_transaction_raw_references_transaction_id'), 'transaction_raw_references',
                    ['transaction_id'], unique=True)
    op.create_index(op.f('ix_transaction_raw_references_raw_source_type'), 'transaction_raw_references',
                    ['raw_source_type'], unique=False)
    op.create_index(op.f('ix_transaction_raw_references_raw_source_id'), 'transaction_raw_references',
                    ['raw_source_id'], unique=False)
    op.create_index(op.f('ix_transaction_raw_references_id'), 'transaction_raw_references', ['id'], unique=False)
    op.create_index(op.f('idx_raw_ref_source'), 'transaction_raw_references', ['raw_source_type', 'raw_source_id'],
                    unique=False)
    # ### end Alembic commands ###
