#!/bin/bash
# Launch Vault Voyager
# Double-click this file in Finder to start the app.
# On first run, Docker will build the app — this takes ~2 minutes.
# Subsequent launches are fast.

cd "$(dirname "$0")"

# ── Create .env on first run (auto-generate a secure Postgres password) ───────
if [ ! -f .env ]; then
    echo "First run: generating database password..."
    PG_PASS=$(openssl rand -hex 32)
    cat > .env <<ENVEOF
# Auto-generated by Launch Vault Voyager.command on first run.
# Do not commit this file — it is listed in .gitignore.
POSTGRES_PASSWORD=${PG_PASS}
DATABASE_URL=postgresql://ftm_user:${PG_PASS}@db:5432/financial_transactions
ENVEOF
    echo "Secure password written to .env"
fi

# ── Check Docker is installed ──────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    osascript <<'EOF'
display dialog "Docker Desktop is required but is not installed.

Please download and install Docker Desktop from the website, then try again." buttons {"Open docker.com", "Cancel"} default button 1 with icon caution
set btn to button returned of result
if btn is "Open docker.com" then
    open location "https://www.docker.com/products/docker-desktop/"
end if
EOF
    exit 1
fi

# ── Check Docker is running ────────────────────────────────────────────────────
if ! docker info &>/dev/null; then
    osascript <<'EOF'
display dialog "Docker Desktop is installed but not running.

Please open Docker Desktop from your Applications folder, wait for the whale icon to appear in your menu bar, then try again." buttons {"Open Docker Desktop", "Cancel"} default button 1 with icon caution
set btn to button returned of result
if btn is "Open Docker Desktop" then
    tell application "Docker" to activate
end if
EOF
    exit 1
fi

# ── Start the app ──────────────────────────────────────────────────────────────
echo "Starting Vault Voyager..."
docker compose up -d --build 2>&1

if [ $? -ne 0 ]; then
    osascript -e 'display dialog "Failed to start Vault Voyager. Check Docker Desktop for logs." buttons {"OK"} default button 1 with icon stop'
    exit 1
fi

# ── Wait for the app to be ready (up to 60s) ──────────────────────────────────
echo "Waiting for app to be ready..."
for i in $(seq 1 30); do
    if curl -s http://localhost:3002/health &>/dev/null; then
        open "http://localhost:3002"
        osascript -e 'display notification "Vault Voyager is running — opening in your browser." with title "Vault Voyager 🚀"'
        exit 0
    fi
    sleep 2
done

osascript -e 'display dialog "App is taking longer than expected to start.\n\nTry opening http://localhost:3002 in your browser in a moment, or check Docker Desktop for logs." buttons {"OK"} default button 1 with icon caution'
