"""Added Custom Transactions

Revision ID: 919f058d7d1e
Revises: 
Create Date: 2026-02-20 15:36:24.915786

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '919f058d7d1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
