'use strict';

// ── Canonical .env content model ─────────────────────────────────────────────
// Pure string→string helpers for the .env the desktop app owns (it lives at
// `<userData>/embedded_compose/.env`, mode 0600, and is mirrored into the
// compose work dir by ensureEnv() in main.js). Extracted from main.js so the
// two-role upgrade below is unit-testable without booting Electron
// (precedent: backup/bundle.js + tests/backup-roundtrip.test.js).
//
// SECURITY MODEL — least-privilege database role (security backlog: "Backend
// DB role is the Postgres bootstrap superuser"). The .env carries:
//
//   POSTGRES_PASSWORD      the superuser the postgres image bootstraps (ftm_user)
//   DATABASE_URL           that superuser. Used for Alembic DDL, the backend's
//                          runtime role bootstrap, and the pg_dump/psql
//                          backup+restore paths. **NEVER repointed.**
//   POSTGRES_APP_PASSWORD  ftm_app's password, so the compose first-init script
//                          (docker/postgres-init/01-app-role.sh) can create the
//                          same role with the same password when it *does* run
//                          (repo/dev stack on a fresh volume).
//   DATABASE_URL_APP       the non-superuser ftm_app role. A bootstrap-aware
//                          backend moves its runtime pool here after creating
//                          and verifying the role.
//
// DATABASE_URL deliberately keeps naming the PRIVILEGED role. The desktop
// shell and the backend image update independently — the packaged compose pins
// `vision:latest` with `pull_policy: missing`, so a cached older image is not
// re-pulled and APP_IMAGE_TAG is never set by this code — which means a NEW
// shell routinely runs an OLD backend. An old backend has no role bootstrap;
// handing it a DATABASE_URL naming a role that does not exist yet kills boot in
// its DB-readiness loop, and the UI (with the in-app image-update button) never
// loads. An extra variable an old image simply ignores makes the rollout
// structurally skew-proof, with no version coordination required.
//
// Both passwords are 32 random bytes hex — never derived, never logged, and
// (being hex) never contain a quote or a URL-reserved character.

const crypto = require('crypto');

/** The non-superuser role the runtime pool connects as. */
const APP_DB_ROLE = 'ftm_app';

/**
 * Strip one layer of surrounding single/double quotes from a .env value.
 * `DATABASE_URL="postgresql://…"` is a legal (and common) way to write the
 * line; without this the URL fails to parse and the two-role upgrade below
 * silently no-ops forever.
 * @param {string|undefined} value
 */
function unquote(value) {
  if (typeof value !== 'string') return value;
  const trimmed = value.trim();
  if (trimmed.length >= 2) {
    const first = trimmed[0];
    if ((first === '"' || first === "'") && trimmed[trimmed.length - 1] === first) {
      return trimmed.slice(1, -1);
    }
  }
  return trimmed;
}

/** @param {string|null|undefined} contents */
function parseEnvKeys(contents) {
  const map = new Map();
  for (const line of (contents || '').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    map.set(trimmed.slice(0, eq).trim(), trimmed.slice(eq + 1).trim());
  }
  return map;
}

/**
 * Replace `KEY=` in place (preserving line order and comments) or append it.
 * @param {string} contents
 * @param {string} key
 * @param {string} value
 */
function setEnvKey(contents, key, value) {
  const lines = (contents || '').split('\n');
  let replaced = false;
  const next = lines.map((line) => {
    const trimmed = line.trim();
    if (trimmed.startsWith('#')) return line;
    const eq = trimmed.indexOf('=');
    if (eq === -1 || trimmed.slice(0, eq).trim() !== key) return line;
    replaced = true;
    return `${key}=${value}`;
  });
  if (replaced) return next.join('\n');
  const base = contents && !contents.endsWith('\n') ? `${contents}\n` : (contents || '');
  return `${base}${key}=${value}\n`;
}

function randomSecret() {
  return crypto.randomBytes(32).toString('hex');
}

/**
 * A brand-new install's .env: two-role from the very first launch, with
 * DATABASE_URL still on the privileged role so an older cached backend image
 * boots identically to how it always has.
 */
function generateFreshEnvContents() {
  const pgPass = randomSecret();
  const appPass = randomSecret();
  return [
    '# Auto-generated by Vision on first launch. Do not commit this file.',
    `POSTGRES_PASSWORD=${pgPass}`,
    `POSTGRES_APP_PASSWORD=${appPass}`,
    `DATABASE_URL=postgresql://ftm_user:${pgPass}@db:5432/financial_transactions`,
    `DATABASE_URL_APP=postgresql://${APP_DB_ROLE}:${appPass}@db:5432/financial_transactions`,
  ].join('\n') + '\n';
}

/**
 * Add the least-privilege runtime role to an existing single-role .env.
 *
 * Runs on every launch (idempotent) and is PURELY ADDITIVE: DATABASE_URL is
 * never touched, so an older cached backend image reads exactly the value it
 * always did and boots unchanged. The database itself is not touched either —
 * the desktop app has no psql — the backend's own runtime bootstrap
 * (apps/node-backend/src/database/appRoleBootstrap.js) creates/repairs the
 * `ftm_app` role over DATABASE_URL on its next boot, and fails open to the
 * privileged role if anything about that goes wrong. So the worst case of this
 * rewrite is "the app boots exactly as it did before, with a warning in the
 * backend log".
 *
 * Deliberately leaves the file alone when:
 *   - DATABASE_URL_APP is already present (nothing to do, and never
 *     re-generate a password already in use);
 *   - DATABASE_URL is missing or unparseable (nothing safe to derive from);
 *   - DATABASE_URL already names the app role — the hand-rolled layout the
 *     earlier half of this change documented (DATABASE_URL=ftm_app +
 *     DATABASE_URL_MIGRATIONS=ftm_user). That install is already
 *     least-privilege; adding a third URL would be noise.
 *
 * @param {string} contents
 * @returns {string}
 */
function ensureAppRoleEnv(contents) {
  const keys = parseEnvKeys(contents);
  if (keys.has('DATABASE_URL_APP')) return contents;

  const raw = unquote(keys.get('DATABASE_URL'));
  if (!raw) return contents;

  let url;
  try {
    url = new URL(raw);
  } catch {
    return contents;
  }
  const currentUser = decodeURIComponent(url.username || '');
  if (!currentUser || currentUser === APP_DB_ROLE) return contents;

  // Reuse an already-generated app password if one is sitting in the file
  // (e.g. the user set POSTGRES_APP_PASSWORD for the compose init script
  // before ever launching the desktop app) so both paths agree on the secret.
  const appPass = unquote(keys.get('POSTGRES_APP_PASSWORD')) || randomSecret();

  const appUrl = new URL(raw);
  appUrl.username = APP_DB_ROLE;
  appUrl.password = appPass;

  let next = contents;
  next = setEnvKey(next, 'POSTGRES_APP_PASSWORD', appPass);
  next = setEnvKey(next, 'DATABASE_URL_APP', appUrl.toString());
  return next;
}

module.exports = {
  APP_DB_ROLE,
  unquote,
  parseEnvKeys,
  setEnvKey,
  generateFreshEnvContents,
  ensureAppRoleEnv,
};
