'use strict';

const { app, BrowserWindow, dialog, Notification, shell, ipcMain } = require('electron');
const { execFile } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const http = require('http');
// Small i18n loader for main process dialogs
const I18N_DIR = path.join(__dirname, 'i18n');
function loadI18n() {
  const locale = (app && app.getLocale && typeof app.getLocale === 'function') ? app.getLocale() : 'en';
  const lang = locale && locale.startsWith('nl') ? 'nl' : 'en';
  try {
    const p = path.join(I18N_DIR, `${lang}.json`);
    if (fs.existsSync(p)) {
      return JSON.parse(fs.readFileSync(p, 'utf8'));
    }
  } catch (e) {
    // fallthrough
  }
  try {
    const p2 = path.join(I18N_DIR, 'en.json');
    if (fs.existsSync(p2)) return JSON.parse(fs.readFileSync(p2, 'utf8'));
  } catch (e) {}
  return {};
}

const i18n = loadI18n();
function t(key, vars) {
  let txt = i18n[key] || key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) txt = txt.replace(`{${k}}`, v);
  }
  return txt;
}

// electron-updater is a production dependency — loaded only in packaged builds
// to avoid errors during development where it isn't installed via npm.
let autoUpdater = null;
try {
  autoUpdater = require('electron-updater').autoUpdater;
} catch {
  // Running in dev without electron-updater installed — no-op
}

// ── Constants ─────────────────────────────────────────────────────────────────
const APP_NAME = 'Vision';
const DEFAULT_APP_PORT = 3002;
const HEALTH_POLL_ATTEMPTS = 30;   // 30 × 2s = 60s max (same as .command files)
const HEALTH_POLL_INTERVAL_MS = 2000;

// Resolved at launch — see findFreePort() below
let appPort = DEFAULT_APP_PORT;
let APP_URL = `http://localhost:${appPort}`;
let HEALTH_URL = `http://localhost:${appPort}/health`;
const GITHUB_OWNER = 'EraPartner';
const GITHUB_REPO = 'Vision';

// ── Port detection ────────────────────────────────────────────────────────────
// Try the preferred port; if it's in use, walk up until a free one is found.
function findFreePort(preferred) {
  return new Promise((resolve) => {
    const net = require('net');
    const tryPort = (port) => {
      const server = net.createServer();
      server.unref();
      server.on('error', () => tryPort(port + 1));
      server.listen(port, '127.0.0.1', () => {
        server.close(() => resolve(port));
      });
    };
    tryPort(preferred);
  });
}

// ── Settings (persisted across launches) ─────────────────────────────────────
const settingsPath = path.join(app.getPath('userData'), 'settings.json');

function loadSettings() {
  try { return JSON.parse(fs.readFileSync(settingsPath, 'utf8')); }
  catch { return {}; }
}

function saveSettings(data) {
  fs.mkdirSync(path.dirname(settingsPath), { recursive: true });
  fs.writeFileSync(settingsPath, JSON.stringify(data, null, 2));
}

// ── Repo/workDir resolution ───────────────────────────────────────────────────
// In dev (electron . from packaging/electron/): resolve two levels up.
// In packaged .app: uses embedded docker-compose.yml shipped in app resources.
async function resolveWorkDir() {
  if (!app.isPackaged) {
    return path.resolve(__dirname, '..', '..');
  }

  // If we've already set up the embedded compose, reuse it.
  const settings = loadSettings();
  if (settings.embeddedDir && fs.existsSync(path.join(settings.embeddedDir, 'docker-compose.yml'))) {
    return settings.embeddedDir;
  }

  // Copy embedded compose from resources to a writable app data folder.
  const embeddedSrc = path.join(process.resourcesPath, 'resources', 'docker-compose.yml');
  const embeddedDir = path.join(app.getPath('userData'), 'embedded_compose');
  try {
    fs.mkdirSync(embeddedDir, { recursive: true });
    const dest = path.join(embeddedDir, 'docker-compose.yml');
    // Overwrite if exists to allow updates on new app versions
    fs.copyFileSync(embeddedSrc, dest);
    saveSettings({ ...loadSettings(), embeddedDir });
    return embeddedDir;
  } catch (err) {
    await dialog.showMessageBox({
      type: 'error',
      buttons: [t('common.ok')],
      title: APP_NAME,
      message: t('app.failedPrepareEmbedded'),
      detail: String(err),
    });
    app.quit();
    return null;
  }
}

// ── .env generation ───────────────────────────────────────────────────────────
function ensureEnv(workDir) {
  const envFile = path.join(workDir, '.env');
  if (!fs.existsSync(envFile)) {
    const pgPass = crypto.randomBytes(32).toString('hex');
    const contents = [
      '# Auto-generated by Vision on first launch. Do not commit this file.',
      `POSTGRES_PASSWORD=${pgPass}`,
      `DATABASE_URL=postgresql://ftm_user:${pgPass}@db:5432/financial_transactions`,
    ].join('\n') + '\n';
    fs.writeFileSync(envFile, contents, { encoding: 'utf8', mode: 0o600 });
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────
// Extend PATH so the docker CLI is found when launched as a macOS .app
const dockerEnv = {
  ...process.env,
  PATH: [process.env.PATH, '/usr/local/bin', '/opt/homebrew/bin'].filter(Boolean).join(':'),
};

function run(bin, args, cwd, opts = {}) {
  const { env: envOverride, ...rest } = opts;
  const env = envOverride || dockerEnv;
  return new Promise((resolve, reject) => {
    execFile(bin, args, { env, cwd, ...rest }, (err, stdout, stderr) => {
      if (err) return reject(stderr?.trim() || err.message || String(err));
      resolve(stdout);
    });
  });
}

function notify(body) {
  if (Notification.isSupported()) {
    new Notification({ title: APP_NAME, body }).show();
  }
}

// Poll /health until success or timeout
function pollHealth() {
  return new Promise((resolve, reject) => {
    let tries = 0;
    const attempt = () => {
      const req = http.get(HEALTH_URL, (res) => {
        if (res.statusCode >= 200 && res.statusCode < 400) return resolve();
        res.resume();
        retry();
      });
      req.on('error', retry);
      req.setTimeout(1500, () => { req.destroy(); retry(); });
    };
    const retry = () => {
      if (++tries >= HEALTH_POLL_ATTEMPTS) return reject(new Error('timeout'));
      setTimeout(attempt, HEALTH_POLL_INTERVAL_MS);
    };
    attempt();
  });
}

// ── Docker checks ─────────────────────────────────────────────────────────────
async function checkDockerInstalled(cwd) {
  try { await run('docker', ['--version'], cwd); return true; }
  catch { return false; }
}

async function checkDockerRunning(cwd) {
  try { await run('docker', ['info'], cwd, { timeout: 8000 }); return true; }
  catch { return false; }
}

// ── Docker Compose actions ────────────────────────────────────────────────────
function composeArgs(cwd, extraFiles = []) {
  // Build -f flags: always start with the base docker-compose.yml, then any overrides.
  const files = [
    path.join(cwd, 'docker-compose.yml'),
    ...extraFiles,
  ];
  return files.flatMap(f => ['-f', f]);
}

function startContainers(cwd, extraFiles = []) {
  const args = [
    'compose', ...composeArgs(cwd, extraFiles),
    'up', '-d',
    ...(app.isPackaged ? [] : ['--build']),
  ];
  // Inject the resolved port so docker-compose.yml's ${PORT:-3002} interpolation
  // maps the correct host port → container 3002.
  const env = { ...dockerEnv, PORT: String(appPort) };
  return run('docker', args, cwd, { timeout: 300000, env });
}

function stopContainers(cwd, extraFiles = []) {
  const args = ['compose', ...composeArgs(cwd, extraFiles), 'down'];
  return run('docker', args, cwd, { timeout: 60000 });
}

// Pull the latest Docker image tag for the app service without stopping the DB.
// Returns true if a new image was pulled, false if already up to date.
async function pullLatestImage(cwd) {
  try {
    const output = await run('docker', ['compose', 'pull', 'app'], cwd, { timeout: 120000 });
    // docker compose pull outputs "Pulled" when a new layer was downloaded
    return /pulled/i.test(output);
  } catch (err) {
    console.warn('docker compose pull failed (non-fatal):', err);
    return false;
  }
}

// Restart only the app container (not the db) to pick up the new image.
async function restartAppContainer(cwd, extraFiles = []) {
  const args = ['compose', ...composeArgs(cwd, extraFiles), 'up', '-d', '--no-deps', 'app'];
  await run('docker', args, cwd, { timeout: 120000 });
}

// ── Main window ───────────────────────────────────────────────────────────────
let mainWindow = null;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    title: APP_NAME,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      // Preload exposes a minimal update API to the renderer
      preload: path.join(__dirname, 'preload.js'),
    },
  });
  mainWindow.loadURL(APP_URL);
  mainWindow.on('closed', () => { mainWindow = null; });
}

// ── electron-updater (Electron shell update) ─────────────────────────────────
// This handles updating the macOS .app wrapper itself.
// The app binary update and the Docker image update are independent:
//   • Docker image: pulled on every launch (--pull always) + on demand below
//   • Electron shell: downloaded in background; user prompted to install & restart

function setupAutoUpdater() {
  if (!autoUpdater || !app.isPackaged) return;

  // Disable the default auto-download so we control the UX
  autoUpdater.autoDownload = false;
  autoUpdater.autoInstallOnAppQuit = true;

  autoUpdater.on('update-available', async (info) => {
    const { response } = await dialog.showMessageBox({
      type: 'info',
      buttons: [t('update.download'), t('update.later')],
      defaultId: 0,
      cancelId: 1,
      title: t('update.availableTitle', { app: APP_NAME }),
      message: t('update.versionAvailable', { version: info.version }),
      detail: t('update.detailDownload'),
    });

    if (response === 0) {
      autoUpdater.downloadUpdate();
      notify(t('update.downloading'));
    }
  });

  autoUpdater.on('update-downloaded', async (info) => {
    const { response } = await dialog.showMessageBox({
      type: 'info',
      buttons: [t('update.restartNow'), t('update.later')],
      defaultId: 0,
      cancelId: 1,
      title: t('update.readyTitle', { app: APP_NAME }),
      message: t('update.versionDownloaded', { version: info.version }),
      detail: t('update.detailRestart'),
    });

    if (response === 0) {
      isQuitting = true;
      autoUpdater.quitAndInstall();
    }
  });

  autoUpdater.on('error', (err) => {
    console.warn('Auto-updater error (non-fatal):', err.message);
  });

  // Check for a new Electron shell update silently in the background.
  // A 10-second delay avoids competing with startup I/O.
  setTimeout(() => {
    autoUpdater.checkForUpdates().catch((e) => console.warn('Update check failed:', e.message));
  }, 10_000);
}

// ── Docker image update (called after new Electron version detected) ──────────
async function applyDockerImageUpdate(cwd, extraFiles = []) {
  try {
    notify(t('app.pullingLatestImage'));
    const wasNew = await pullLatestImage(cwd);
    if (wasNew) {
      await restartAppContainer(cwd, extraFiles);
      await pollHealth().catch(() => {});
      notify(t('app.imageUpdated'));
    }
  } catch (err) {
    console.warn('Docker image update failed (non-fatal):', err);
  }
}

// ── IPC: renderer can request a Docker image update ──────────────────────────
ipcMain.handle('update:pull-image', async () => {
  if (!workDir) return { success: false, error: 'workDir not set' };
  try {
    const wasNew = await pullLatestImage(workDir);
    if (wasNew) {
      await restartAppContainer(workDir, overrideFiles);
      await pollHealth().catch(() => {});
    }
    return { success: true, wasNew };
  } catch (err) {
    return { success: false, error: String(err) };
  }
});

ipcMain.handle('update:check-github', async () => {
  try {
    const result = await checkGitHubRelease();
    return result;
  } catch (err) {
    return { error: String(err) };
  }
});

// ── GitHub Releases API helper ────────────────────────────────────────────────
// Used by both the renderer (via IPC) and the Docker image update check.
function checkGitHubRelease() {
  return new Promise((resolve, reject) => {
    const url = `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/releases/latest`;
    const opts = {
      headers: {
        'User-Agent': `${APP_NAME}-desktop/${app.getVersion()}`,
        'Accept': 'application/vnd.github+json',
      },
    };
    require('https').get(url, opts, (res) => {
      let body = '';
      res.on('data', (c) => { body += c; });
      res.on('end', () => {
        try {
          const data = JSON.parse(body);
          resolve({
            latest_version: data.tag_name,
            current_version: `v${app.getVersion()}`,
            up_to_date: data.tag_name === `v${app.getVersion()}`,
            release_notes: data.body || '',
            published_at: data.published_at,
            html_url: data.html_url,
          });
        } catch (e) {
          reject(e);
        }
      });
      res.on('error', reject);
    }).on('error', reject);
  });
}

// ── Compose override (dev modes) ─────────────────────────────────────────────
// Set VISION_COMPOSE_OVERRIDE to a filename (relative to workDir) to layer an
// additional compose file on top of the base — e.g. docker-compose.dev.yml.
// Used by the electron:dev and electron:clean root package.json scripts.
function resolveOverrideFiles(workDir) {
  const override = process.env.VISION_COMPOSE_OVERRIDE;
  if (!override || app.isPackaged) return [];
  // Accept absolute paths too, but the common case is a repo-root filename.
  const resolved = path.isAbsolute(override) ? override : path.join(workDir, override);
  return fs.existsSync(resolved) ? [resolved] : [];
}

// ── Launch flow ───────────────────────────────────────────────────────────────
let workDir = null;
let overrideFiles = [];

async function launch() {
  // 1. Resolve project folder
  workDir = await resolveWorkDir();
  if (!workDir) return;

  // 1b. Resolve any compose override requested via env var (dev flows only)
  overrideFiles = resolveOverrideFiles(workDir);

  // 1c. Find a free host port for the backend (default 3002, auto-increment if taken)
  appPort = await findFreePort(DEFAULT_APP_PORT);
  APP_URL = `http://localhost:${appPort}`;
  HEALTH_URL = `http://localhost:${appPort}/health`;

  // 2. First run: generate .env if missing
  ensureEnv(workDir);

  // 3. Check Docker is installed
  if (!(await checkDockerInstalled(workDir))) {
    const { response } = await dialog.showMessageBox({
      type: 'warning',
      buttons: [t('app.openDockerSite'), t('common.cancel')],
      defaultId: 0,
      title: APP_NAME,
      message: t('app.dockerRequired'),
      detail: t('app.dockerRequiredDetail'),
    });
    if (response === 0) shell.openExternal('https://www.docker.com/products/docker-desktop/');
    app.quit();
    return;
  }

  // 4. Check Docker daemon is running
  if (!(await checkDockerRunning(workDir))) {
    const { response } = await dialog.showMessageBox({
      type: 'warning',
      buttons: [t('app.openDockerApp'), t('common.cancel')],
      defaultId: 0,
      title: APP_NAME,
      message: t('app.dockerNotRunning'),
      detail: t('app.dockerNotRunningDetail'),
    });
    if (response === 0) shell.openPath('/Applications/Docker.app');
    app.quit();
    return;
  }

  // 5. docker compose up  (packaged: --pull always; dev: --build)
  try {
    await startContainers(workDir, overrideFiles);
  } catch (err) {
    await dialog.showMessageBox({
      type: 'error',
      buttons: [t('common.ok')],
      title: APP_NAME,
      message: t('app.failedStart'),
      detail: `${t('app.checkDockerLogs')}\n\n${String(err)}`,
    });
    app.quit();
    return;
  }

  // 6. Poll /health
  try {
    await pollHealth();
    createWindow();
    notify(t('app.running'));
  } catch (_) {
    await dialog.showMessageBox({
      type: 'warning',
      buttons: [t('common.ok')],
      title: APP_NAME,
      message: t('app.startSlow'),
      detail: t('app.startSlowDetail', { url: APP_URL }),
    });
    createWindow();
  }

  // 7. Set up electron-updater (non-blocking — runs in background after window opens)
  setupAutoUpdater();
}

// ── Shutdown flow ─────────────────────────────────────────────────────────────
let isQuitting = false;

app.on('will-quit', (e) => {
  if (isQuitting || !workDir) return;
  e.preventDefault();
  isQuitting = true;

  stopContainers(workDir, overrideFiles)
    .catch((err) => console.error('docker compose down failed:', err))
    .finally(() => {
      notify(t('app.stopped'));
      app.exit(0);
    });
});

// ── App lifecycle ─────────────────────────────────────────────────────────────
app.whenReady().then(launch);

app.on('activate', () => {
  if (mainWindow === null) createWindow();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
