'use strict';

const { app, BrowserWindow, dialog, Notification, shell } = require('electron');
const { execFile } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const http = require('http');

// ── Constants ─────────────────────────────────────────────────────────────────
const APP_NAME = 'Vision';
const APP_PORT = 3002;
const APP_URL = `http://localhost:${APP_PORT}`;
const HEALTH_URL = `http://localhost:${APP_PORT}/health`;
const HEALTH_POLL_ATTEMPTS = 30;   // 30 × 2s = 60s max (same as .command files)
const HEALTH_POLL_INTERVAL_MS = 2000;

// ── Settings (persisted across launches) ─────────────────────────────────────
const settingsPath = path.join(app.getPath('userData'), 'settings.json');

function loadSettings() {
  try { return JSON.parse(fs.readFileSync(settingsPath, 'utf8')); }
  catch { return {}; }
}

function saveSettings(data) {
  fs.mkdirSync(path.dirname(settingsPath), { recursive: true });
  fs.writeFileSync(settingsPath, JSON.stringify(data, null, 2));
}

// ── Repo/workDir resolution ───────────────────────────────────────────────────
// Mirrors how .command files do: cd "$(dirname "$0")" to get the repo root.
// In dev (electron . from packaging/electron/): resolve two levels up.
// In packaged .app: the user has source, so we prompt once and remember.
async function resolveWorkDir() {
  // In dev mode use the repo (two levels up). In packaged mode we use an
  // embedded docker-compose.yml shipped in the app resources so the user
  // does not need to choose a folder.
  if (!app.isPackaged) {
    return path.resolve(__dirname, '..', '..');
  }

  // If we've already set up the embedded compose, reuse it.
  const settings = loadSettings();
  if (settings.embeddedDir && fs.existsSync(path.join(settings.embeddedDir, 'docker-compose.yml'))) {
    return settings.embeddedDir;
  }

  // Copy embedded compose from resources to a writable app data folder.
  const embeddedSrc = path.join(process.resourcesPath, 'resources', 'docker-compose.yml');
  const embeddedDir = path.join(app.getPath('userData'), 'embedded_compose');
  try {
    fs.mkdirSync(embeddedDir, { recursive: true });
    const dest = path.join(embeddedDir, 'docker-compose.yml');
    // Overwrite if exists to allow updates on new app versions
    fs.copyFileSync(embeddedSrc, dest);
    saveSettings({ ...loadSettings(), embeddedDir });
    return embeddedDir;
  } catch (err) {
    await dialog.showMessageBox({
      type: 'error',
      buttons: ['OK'],
      title: APP_NAME,
      message: 'Failed to prepare embedded resources.',
      detail: String(err),
    });
    app.quit();
    return null;
  }
}

// ── .env generation ───────────────────────────────────────────────────────────
// Mirrors the first-run block in Launch Vault Voyager.command:
//   if [ ! -f .env ]; then PG_PASS=$(openssl rand -hex 32) ...
function ensureEnv(workDir) {
  const envFile = path.join(workDir, '.env');
  if (!fs.existsSync(envFile)) {
    const pgPass = crypto.randomBytes(32).toString('hex'); // equivalent to openssl rand -hex 32
    const contents = [
      '# Auto-generated by Vision on first launch. Do not commit this file.',
      `POSTGRES_PASSWORD=${pgPass}`,
      `DATABASE_URL=postgresql://ftm_user:${pgPass}@db:5432/financial_transactions`,
    ].join('\n') + '\n';
    fs.writeFileSync(envFile, contents, { encoding: 'utf8', mode: 0o600 });
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────
// Extend PATH so the docker CLI is found when launched as a macOS .app
// (macOS apps inherit a minimal PATH that often misses /usr/local/bin).
const dockerEnv = {
  ...process.env,
  PATH: [process.env.PATH, '/usr/local/bin', '/opt/homebrew/bin'].filter(Boolean).join(':'),
};

function run(bin, args, cwd, opts = {}) {
  return new Promise((resolve, reject) => {
    execFile(bin, args, { env: dockerEnv, cwd, ...opts }, (err, stdout, stderr) => {
      if (err) return reject(stderr?.trim() || err.message || String(err));
      resolve(stdout);
    });
  });
}

function notify(body) {
  if (Notification.isSupported()) {
    new Notification({ title: APP_NAME, body }).show();
  }
}

// Poll /health until success or timeout (mirrors the loop in .command)
function pollHealth() {
  return new Promise((resolve, reject) => {
    let tries = 0;
    const attempt = () => {
      const req = http.get(HEALTH_URL, (res) => {
        if (res.statusCode >= 200 && res.statusCode < 400) return resolve();
        res.resume();
        retry();
      });
      req.on('error', retry);
      req.setTimeout(1500, () => { req.destroy(); retry(); });
    };
    const retry = () => {
      if (++tries >= HEALTH_POLL_ATTEMPTS) return reject(new Error('timeout'));
      setTimeout(attempt, HEALTH_POLL_INTERVAL_MS);
    };
    attempt();
  });
}

// ── Docker checks (mirrors command -v docker and docker info in .command) ─────
async function checkDockerInstalled(cwd) {
  try { await run('docker', ['--version'], cwd); return true; }
  catch { return false; }
}

async function checkDockerRunning(cwd) {
  try { await run('docker', ['info'], cwd, { timeout: 8000 }); return true; }
  catch { return false; }
}

// ── Docker Compose actions ────────────────────────────────────────────────────
function startContainers(cwd) {
  // Same flags as .command: docker compose up -d --build
  return run('docker', ['compose', 'up', '-d', '--build'], cwd, { timeout: 300000 });
}

function stopContainers(cwd) {
  // Same as .command: docker compose down
  return run('docker', ['compose', 'down'], cwd, { timeout: 60000 });
}

// ── Main window ───────────────────────────────────────────────────────────────
let mainWindow = null;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    title: APP_NAME,
    webPreferences: { nodeIntegration: false, contextIsolation: true },
  });
  mainWindow.loadURL(APP_URL);
  mainWindow.on('closed', () => { mainWindow = null; });
}

// ── Launch flow (mirrors Launch Vault Voyager.command) ────────────────────────
let workDir = null;

async function launch() {
  // 1. Resolve project folder (equivalent to cd "$(dirname "$0")")
  workDir = await resolveWorkDir();
  if (!workDir) return;

  // 2. First run: generate .env if missing
  ensureEnv(workDir);

  // 3. Check Docker is installed
  if (!(await checkDockerInstalled(workDir))) {
    const { response } = await dialog.showMessageBox({
      type: 'warning',
      buttons: ['Open docker.com', 'Cancel'],
      defaultId: 0,
      title: APP_NAME,
      message: 'Docker Desktop is required but is not installed.',
      detail: 'Please download and install Docker Desktop, then relaunch Vision.',
    });
    if (response === 0) shell.openExternal('https://www.docker.com/products/docker-desktop/');
    app.quit();
    return;
  }

  // 4. Check Docker daemon is running (docker info)
  if (!(await checkDockerRunning(workDir))) {
    const { response } = await dialog.showMessageBox({
      type: 'warning',
      buttons: ['Open Docker Desktop', 'Cancel'],
      defaultId: 0,
      title: APP_NAME,
      message: 'Docker Desktop is installed but not running.',
      detail: 'Please open Docker Desktop, wait for the whale icon to appear in the menu bar, then relaunch Vision.',
    });
    if (response === 0) shell.openPath('/Applications/Docker.app');
    app.quit();
    return;
  }

  // 5. docker compose up -d --build
  try {
    await startContainers(workDir);
  } catch (err) {
    await dialog.showMessageBox({
      type: 'error',
      buttons: ['OK'],
      title: APP_NAME,
      message: 'Failed to start Vision.',
      detail: `Check Docker Desktop for logs.\n\n${err}`,
    });
    app.quit();
    return;
  }

  // 6. Poll /health (up to 30 × 2s = 60s, same as .command)
  try {
    await pollHealth();
    createWindow();
    notify('Vision is running.');
  } catch (_) {
    // Mirrors .command caution dialog on timeout
    await dialog.showMessageBox({
      type: 'warning',
      buttons: ['OK'],
      title: APP_NAME,
      message: 'App is taking longer than expected to start.',
      detail: `Try opening ${APP_URL} in your browser in a moment, or check Docker Desktop for logs.`,
    });
    createWindow(); // open the window anyway; user can wait/refresh
  }
}

// ── Shutdown flow (mirrors Stop Vault Voyager.command) ────────────────────────
let isQuitting = false;

app.on('will-quit', (e) => {
  if (isQuitting || !workDir) return;
  e.preventDefault();
  isQuitting = true;

  stopContainers(workDir)
    .catch((err) => console.error('docker compose down failed:', err))
    .finally(() => {
      notify('Vision has been stopped.');
      app.exit(0);
    });
});

// ── App lifecycle ─────────────────────────────────────────────────────────────
app.whenReady().then(launch);

// Re-show window if user clicks dock icon after closing it (macOS convention)
app.on('activate', () => {
  if (mainWindow === null) createWindow();
});

// On macOS keep the process alive until explicit quit (Cmd+Q / dock → Quit)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
