#!/usr/bin/env bash
# Runs once when the devcontainer is first created, as the `dev` user.
# Installs JS + Python deps and seeds config. Postgres init/start + role/db
# creation now happen in the root ENTRYPOINT (no sudo here — the container runs
# with no-new-privileges).

set -euo pipefail
cd /workspaces/Vision

# Wait for the egress proxy (started by the root entrypoint) before any network
# install — postCreate can race the entrypoint's proxy startup, and with egress
# locked to the proxy UID, installs fail until 127.0.0.1:3128 is listening.
echo "[post-create] Waiting for egress proxy on 127.0.0.1:3128..."
for _ in $(seq 1 30); do
  (exec 3<>/dev/tcp/127.0.0.1/3128) 2>/dev/null && break
  sleep 1
done

# Supply-chain protection: install Aikido safe-chain so package installs are
# screened against its malware list (malware-list.aikido.dev, allowlisted in
# squid). `safe-chain setup` writes shell wrappers; BASH_ENV (devcontainer.json)
# sources them into every bash session so npm/bun/pip installs Claude runs
# mid-session are screened. The project's own pinned deps below are installed
# plain (already vetted via the lockfile) to avoid first-boot fragility.
echo "[post-create] Installing safe-chain (supply-chain protection)..."
if npm install -g @aikidosec/safe-chain >/dev/null 2>&1 && command -v safe-chain >/dev/null 2>&1; then
  safe-chain setup >/dev/null 2>&1 || true
  echo "[post-create] safe-chain installed (screens npm/bun/pip in later sessions)."
else
  echo "[post-create] WARN: safe-chain install failed — continuing without it." >&2
fi

# Python venv for alembic. The repo's scripts expect ./venv. A host-side (macOS)
# venv has Linux-invalid symlinks — rebuild if broken. .gitignore covers venv/.
if [[ ! -x ./venv/bin/python ]] || ! ./venv/bin/python -c '' 2>/dev/null; then
  echo "[post-create] Rebuilding Python venv (host symlinks invalid in container)..."
  rm -rf ./venv
  python3 -m venv venv
fi
# pip honors HTTPS_PROXY → squid → pypi.org / files.pythonhosted.org.
./venv/bin/pip install --quiet --upgrade pip
./venv/bin/pip install --quiet -r config/requirements.txt

# Local .env — only generated if missing. Devcontainer env vars already point
# the backend at the local cluster; this is for tooling that reads .env directly.
if [[ ! -f .env ]]; then
  echo "[post-create] Writing .env (devcontainer defaults)..."
  cat > .env <<'EOF'
# Generated by .devcontainer/post-create.sh — safe to edit.
POSTGRES_PASSWORD=localdev
DATABASE_URL=postgresql://ftm_user:localdev@127.0.0.1:5432/financial_transactions
DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=ftm_user
DB_NAME=financial_transactions
LOG_LEVEL=info
ENABLE_LOGGING=true
EOF
fi

# Install JS deps (bun honors HTTPS_PROXY → squid → registry.npmjs.org).
echo "[post-create] bun install..."
bun install

# Alembic migrations are intentionally NOT run here — the Node backend
# pre-creates alembic_version as VARCHAR(64) before invoking alembic (see
# apps/node-backend/src/database/migrate.js). Mirrors the prod entrypoint.

# Build a writable ~/.gitconfig that includes the bind-mounted host gitconfig
# and marks the workspace safe + overrides the signing key path.
if [[ ! -f /home/dev/.gitconfig || ! -s /home/dev/.gitconfig ]]; then
  cat > /home/dev/.gitconfig <<'EOF'
[include]
    path = /home/dev/.gitconfig-host
[safe]
    directory = /workspaces/Vision
# Override the host's signingkey path — that path (/Users/.../ssh/github.pub)
# doesn't resolve inside the container. The public key is bind-mounted to a
# container-local path; the private key stays on the host and ssh-keygen
# reaches it through SSH_AUTH_SOCK (forwarded host ssh-agent).
[user]
    signingkey = /home/dev/.ssh/host-signing.pub
EOF
fi

# Seed the container's ~/.claude + ~/.claude.json from the SANITIZED staging
# dir the host wrapper produced at /home/dev/.claude-stage (bind RO). The
# wrapper strips secrets (.credentials.json) and active code-exec config
# (hooks/mcpServers/enabledPlugins), so a compromised host config can't
# silently propagate executable config into the container.
STAGE=/home/dev/.claude-stage
if [[ ! -f /home/dev/.claude/settings.json && -d "$STAGE/dot-claude" ]]; then
  echo "[post-create] Seeding ~/.claude from sanitized stage..."
  if ! rsync -a --ignore-errors "$STAGE/dot-claude/" /home/dev/.claude/; then
    echo "[post-create] WARN: ~/.claude rsync seed had errors (some files may be missing)." >&2
  fi
  echo "[post-create] Seeded $(find /home/dev/.claude -mindepth 1 -maxdepth 1 | wc -l) entries into ~/.claude."
fi
if [[ ! -f /home/dev/.claude.json && -f "$STAGE/claude.json" ]]; then
  cp "$STAGE/claude.json" /home/dev/.claude.json
  chmod 0600 /home/dev/.claude.json
fi

# gh authenticates via GH_TOKEN forwarded from the host Keychain by the wrapper.
if ! gh auth status >/dev/null 2>&1; then
  cat <<'NOTE'
[post-create] gh is not authenticated. The wrapper forwards GH_TOKEN from your
              host Keychain entry `vision-gh-token` if present. To set it up,
              on the HOST run once:
                gh auth token | security add-generic-password \
                  -s vision-gh-token -a "$USER" -w
              (or paste a PAT). Then re-run `vision-claude`.
NOTE
fi

echo "[post-create] Done."
echo "[post-create] Start the stack with:  bun run dev"
echo "[post-create] Start Claude with:     claude --dangerously-skip-permissions"
