/**
 * Desktop `.env` content model — the writer that decides which DB roles a
 * desktop install runs as (packaging/electron/envConfig.js).
 *
 * The module is CommonJS and lives outside this workspace, so it is loaded via
 * createRequire — same seam as tests/backup-roundtrip.test.js.
 *
 * These assertions are the desktop half of the least-privilege change:
 * a brand-new install must be two-role from its first launch, and an EXISTING
 * install's .env (the only thing an already-shipped Vision.app has) must be
 * upgraded in place, idempotently, without inventing credentials the operator
 * did not ask for.
 *
 * The load-bearing invariant is that the upgrade is PURELY ADDITIVE.
 * DATABASE_URL must keep naming the privileged role: the desktop shell and the
 * backend image update independently (the packaged compose pins
 * `vision:latest` with `pull_policy: missing`), so a new shell routinely runs
 * an OLD backend image that reads only DATABASE_URL and has no role bootstrap.
 * Repointing it would kill that backend's boot in its DB-readiness loop, with
 * the UI — and the in-app image-update button — never reachable.
 */

import { describe, expect, it } from 'vitest';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const require = createRequire(import.meta.url);
const {
  APP_DB_ROLE,
  unquote,
  parseEnvKeys,
  setEnvKey,
  generateFreshEnvContents,
  ensureAppRoleEnv,
} = require(path.join(REPO_ROOT, 'packaging/electron/envConfig.js'));

const LEGACY_ENV =
  '# Auto-generated by Vision on first launch. Do not commit this file.\n' +
  'POSTGRES_PASSWORD=aaaabbbbccccdddd\n' +
  'DATABASE_URL=postgresql://ftm_user:aaaabbbbccccdddd@db:5432/financial_transactions\n' +
  'FRED_API_KEY=abc\n';

describe('electron envConfig: setEnvKey', () => {
  it('replaces an existing key in place and leaves comments alone', () => {
    const out = setEnvKey('# note\nA=1\nB=2\n', 'A', '9');
    expect(out).toBe('# note\nA=9\nB=2\n');
  });

  it('appends a missing key, adding the trailing newline when needed', () => {
    expect(setEnvKey('A=1', 'B', '2')).toBe('A=1\nB=2\n');
  });

  it('does not treat a commented-out key as present', () => {
    const out = setEnvKey('# A=1\n', 'A', '2');
    expect(parseEnvKeys(out).get('A')).toBe('2');
  });
});

describe('electron envConfig: unquote', () => {
  it('strips one layer of surrounding quotes', () => {
    expect(unquote('"postgresql://a:b@db/c"')).toBe('postgresql://a:b@db/c');
    expect(unquote("'postgresql://a:b@db/c'")).toBe('postgresql://a:b@db/c');
    expect(unquote('  postgresql://a:b@db/c  ')).toBe('postgresql://a:b@db/c');
    expect(unquote('"mismatched\'')).toBe('"mismatched\'');
  });
});

describe('electron envConfig: fresh installs', () => {
  it('generates a two-role .env with distinct random secrets', () => {
    const contents = generateFreshEnvContents();
    const keys = parseEnvKeys(contents);

    const pgPass = keys.get('POSTGRES_PASSWORD');
    const appPass = keys.get('POSTGRES_APP_PASSWORD');
    expect(pgPass).toMatch(/^[0-9a-f]{64}$/);
    expect(appPass).toMatch(/^[0-9a-f]{64}$/);
    expect(appPass).not.toBe(pgPass);

    // DATABASE_URL → the privileged role (what an old backend image reads);
    // DATABASE_URL_APP → the non-superuser runtime role.
    expect(keys.get('DATABASE_URL')).toBe(
      `postgresql://ftm_user:${pgPass}@db:5432/financial_transactions`,
    );
    expect(keys.get('DATABASE_URL_APP')).toBe(
      `postgresql://${APP_DB_ROLE}:${appPass}@db:5432/financial_transactions`,
    );
    // Nothing writes the back-compat alias anymore.
    expect(keys.has('DATABASE_URL_MIGRATIONS')).toBe(false);
  });

  it('never generates the same secrets twice', () => {
    expect(generateFreshEnvContents()).not.toBe(generateFreshEnvContents());
  });
});

describe('electron envConfig: upgrading an existing install', () => {
  it('NEVER repoints DATABASE_URL — an older backend image must keep booting', () => {
    const upgraded = ensureAppRoleEnv(LEGACY_ENV);
    const keys = parseEnvKeys(upgraded);

    // The single most important assertion in this file.
    expect(keys.get('DATABASE_URL')).toBe(
      'postgresql://ftm_user:aaaabbbbccccdddd@db:5432/financial_transactions',
    );
    expect(keys.get('POSTGRES_PASSWORD')).toBe('aaaabbbbccccdddd');
    // Unrelated keys survive.
    expect(keys.get('FRED_API_KEY')).toBe('abc');
  });

  it('adds DATABASE_URL_APP for the app role with a fresh strong password', () => {
    const keys = parseEnvKeys(ensureAppRoleEnv(LEGACY_ENV));
    const appPass = keys.get('POSTGRES_APP_PASSWORD');
    expect(appPass).toMatch(/^[0-9a-f]{64}$/);
    expect(appPass).not.toBe('aaaabbbbccccdddd');
    expect(keys.get('DATABASE_URL_APP')).toBe(
      `postgresql://${APP_DB_ROLE}:${appPass}@db:5432/financial_transactions`,
    );
  });

  it('upgrades a QUOTED DATABASE_URL instead of silently no-opping forever', () => {
    const quoted =
      'POSTGRES_PASSWORD=aaaabbbbccccdddd\n' +
      'DATABASE_URL="postgresql://ftm_user:aaaabbbbccccdddd@db:5432/financial_transactions"\n';
    const keys = parseEnvKeys(ensureAppRoleEnv(quoted));
    expect(keys.get('DATABASE_URL_APP')).toContain(`${APP_DB_ROLE}:`);
    // …and the quoted original is left exactly as the operator wrote it.
    expect(keys.get('DATABASE_URL')).toBe(
      '"postgresql://ftm_user:aaaabbbbccccdddd@db:5432/financial_transactions"',
    );
  });

  it('is idempotent — a second launch does not rotate the password', () => {
    const once = ensureAppRoleEnv(LEGACY_ENV);
    const twice = ensureAppRoleEnv(once);
    expect(twice).toBe(once);
  });

  it('reuses a POSTGRES_APP_PASSWORD the operator already set (compose init parity)', () => {
    const withApp = `${LEGACY_ENV}POSTGRES_APP_PASSWORD=preset-secret\n`;
    const keys = parseEnvKeys(ensureAppRoleEnv(withApp));
    expect(keys.get('POSTGRES_APP_PASSWORD')).toBe('preset-secret');
    expect(keys.get('DATABASE_URL_APP')).toContain(`${APP_DB_ROLE}:preset-secret@`);
  });

  it('leaves a .env that already declares DATABASE_URL_APP untouched', () => {
    const already =
      'DATABASE_URL=postgresql://ftm_user:pw@db:5432/financial_transactions\n' +
      `DATABASE_URL_APP=postgresql://${APP_DB_ROLE}:pw2@db:5432/financial_transactions\n`;
    expect(ensureAppRoleEnv(already)).toBe(already);
  });

  it('leaves the hand-rolled layout (DATABASE_URL already on the app role) untouched', () => {
    const manual =
      `DATABASE_URL=postgresql://${APP_DB_ROLE}:pw@db:5432/financial_transactions\n` +
      'DATABASE_URL_MIGRATIONS=postgresql://ftm_user:pw2@db:5432/financial_transactions\n';
    expect(ensureAppRoleEnv(manual)).toBe(manual);
  });

  it('does nothing when DATABASE_URL is missing or unparseable', () => {
    expect(ensureAppRoleEnv('POSTGRES_PASSWORD=x\n')).toBe('POSTGRES_PASSWORD=x\n');
    expect(ensureAppRoleEnv('DATABASE_URL=not a url\n')).toBe('DATABASE_URL=not a url\n');
  });
});
