import type { BelgianTaxProfile } from "../types";

export function makeTaxProfile(
    overrides: Partial<BelgianTaxProfile> = {},
): BelgianTaxProfile {
    return {
        profileConfigured: true,
        employmentType: "employee",
        grossAnnualIncome: 50_000,
        professionalExpenseMethod: "lump_sum",
        actualProfessionalExpenses: 0,
        communalSurchargePercent: 7,
        region: "flanders",
        dependentChildren: 0,
        dependentChildrenUnder3: 0,
        dependentOtherPersons: 0,
        isDisabled: false,
        isSpouseDisabled: false,
        isIsolatedParent: false,
        cadastralIncome: 0,
        additionalResidences: [],
        otherTaxableIncome: 0,
        alimonyPaid: 0,
        personalPensionContributions: 0,
        pensionScheme: "1050",
        pensionEligible: false,
        lifeInsurancePremiums: 0,
        lifeInsuranceEligible: false,
        mortgageInterestPaid: 0,
        charitableDonations: 0,
        charitableDonationsEligible: false,
        childcareCosts: 0,
        childcareEligibleDays: 0,
        childcareEligible: false,
        employeeGroupInsuranceContributions: 0,
        employeeGroupInsuranceEligible: false,
        unionDues: 0,
        medicalExpenses: 0,
        domesticHelpCosts: 0,
        domesticHelpEligible: false,
        annualDividendIncome: 0,
        annualSavingsInterest: 0,
        taxYear: 2025,
        ...overrides,
    };
}
